import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import localFont from "next/font/local";
import { DM_Sans } from "next/font/google";
import SmoothScrolling from "@/components/smooth-scrolling";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-dm-sans",
});

const trap = localFont({
  src: [
    {
      path: '../../public/font/trap/Trap-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../../public/font/trap/Trap-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/font/trap/Trap-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/font/trap/Trap-SemiBold.woff2',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/font/trap/Trap-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/font/trap/Trap-ExtraBold.woff2',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/font/trap/Trap-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-trap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${trap.variable} ${dmSans.variable} font-sans antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <main className="w-full h-screen select-none">
            <SmoothScrolling>
              {children}
            </SmoothScrolling>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
